// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type Feed struct {
	ID          int64
	Title       string
	Description string
	Url         string
	FeedUrl     string
	ChannelID   sql.NullString
}

type Post struct {
	PostGuid    string
	FeedID      int64
	Title       string
	Description string
	Url         string
	MessageID   string
}
